name: pos
description: Developed by Asmiksoft Innovation, www.asmiksoft.com.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.0.1
  data_table_2: ^2.5.6
  date_format: ^2.0.7
  dropdown_search: ^5.0.6
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_launcher_icons: ^0.13.1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^22.2.9
  time: ^2.1.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
